In [14]:
import sys
sys.executable

'C:\\Users\\munsl\\venvs\\credit-ml\\Scripts\\python.exe'

In [15]:
import pandas as pd

df_raw = pd.read_excel("../data/default of credit card clients.xls", header=None)
df_raw.head(3)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,NaN,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
1,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
2,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1

This data is raw, it has the column names on row 1 but they could be in row 0. Row 0 currentyl has generic labels. I will fix this by choosing a header value.

In [16]:
df = pd.read_excel("../data/default of credit card clients.xls", header=1)
df.head(3)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0

I chose header=1 because row 0 had all the generic X1,X2,X3... labels, and row 1 clearly had all the real names I need.

In [17]:
df.shape

(30000, 25)

I expected 23 features but got 25. This is due to the ID column being a row counter and the default payment next month column is the thing I'm trying to predict.